import { Product, User, Transaction, BackupItem, AuditLogItem, SystemSettings, ShopifySyncAlert } from './types'

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'System Admin',
    username: 'admin',
    email: 'amankamran2004@outlook.com',
    password: 'adminpassword',
    role: 'system_admin',
    status: 'active',
    lastLogin: '2026-09-26 09:30 AM',
    createdAt: '2026-01-01',
  },
  {
    id: 'usr-editor-2',
    name: 'Inventory Editor',
    username: 'editor',
    email: 'editor@snugnplay.com',
    password: 'password123',
    role: 'inventory_editor',
    status: 'active',
    lastLogin: '2026-09-26 09:15 AM',
    createdAt: '2026-01-05',
  },
  {
    id: 'usr-ops-3',
    name: 'Operations Team',
    username: 'operations',
    email: 'operations@snugnplay.com',
    password: 'password123',
    role: 'operations',
    status: 'active',
    lastLogin: '2026-09-26 08:45 AM',
    createdAt: '2026-02-01',
  },
  {
    id: 'usr-acc-4',
    name: 'Accounts Team',
    username: 'accounts',
    email: 'accounts@snugnplay.com',
    password: 'password123',
    role: 'accounts',
    status: 'active',
    lastLogin: '2026-09-24 11:20 AM',
    createdAt: '2026-02-15',
  },
  {
    id: 'usr-mgr-5',
    name: 'Sarah Khan (Manager)',
    username: 'manager',
    email: 'manager@snugnplay.com',
    password: 'password123',
    role: 'manager',
    status: 'active',
    lastLogin: '2026-09-25 04:15 PM',
    createdAt: '2026-01-10',
  },
  {
    id: 'usr-view-6',
    name: 'Store Viewer',
    username: 'viewer',
    email: 'viewer@snugnplay.com',
    password: 'password123',
    role: 'viewer',
    status: 'active',
    lastLogin: '2026-09-26 07:00 AM',
    createdAt: '2026-03-01',
  },
]

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    sku: 'SNP-SP-001',
    name: 'Pastel Modular Soft Play Climb & Crawl Set (5-Piece)',
    category: 'Soft Play Equipment',
    brand: 'Snug N Play Original',
    supplier: 'PlaySafe Foam Ltd',
    warehouse: 'Main Hub - Karachi',
    quantity: 42,
    minStock: 10,
    maxStock: 100,
    status: 'in_stock',
    isActive: true,
    notes: 'Bestseller foam shapes with wipe-clean vegan leather cover.',
    updatedAt: '2026-09-25',
    shopifySynced: true,
    shopifyStock: 42,
  },
  {
    id: 'prod-102',
    sku: 'SNP-BP-002',
    name: 'Luxury Velvet Ball Pit with 200 Non-Toxic Pearl Balls',
    category: 'Ball Pits & Playsets',
    brand: 'Snug N Play Luxury',
    supplier: 'SafePlast Toys',
    warehouse: 'Main Hub - Karachi',
    quantity: 18,
    minStock: 10,
    maxStock: 60,
    status: 'in_stock',
    isActive: true,
    notes: 'Memory foam base with washable velvet cover.',
    updatedAt: '2026-09-24',
    shopifySynced: true,
    shopifyStock: 18,
  },
  {
    id: 'prod-103',
    sku: 'SNP-MAT-003',
    name: 'Double-Sided Foldable Waterproof Baby Play Mat (200x180cm)',
    category: 'Play Mats & Rugs',
    brand: 'Snug N Play Care',
    supplier: 'EcoFoam Industries',
    warehouse: 'Lahore Depot',
    quantity: 8,
    minStock: 15,
    maxStock: 80,
    status: 'low_stock',
    isActive: true,
    notes: 'XPE High-density foam, non-slip reversible design.',
    updatedAt: '2026-09-26',
    shopifySynced: true,
    shopifyStock: 8,
  },
  {
    id: 'prod-104',
    sku: 'SNP-WD-004',
    name: 'Montessori Wooden Balance Board & Rocker (Natural Beechwood)',
    category: 'Wooden & Montessori Toys',
    brand: 'Snug Woodcraft',
    supplier: 'CraftWood Artisans',
    warehouse: 'Islamabad Center',
    quantity: 25,
    minStock: 8,
    maxStock: 50,
    status: 'in_stock',
    isActive: true,
    notes: 'Holds up to 100kg weight capacity with felt bottom.',
    updatedAt: '2026-09-22',
    shopifySynced: true,
    shopifyStock: 25,
  },
  {
    id: 'prod-105',
    sku: 'SNP-PL-005',
    name: 'Sensory Weighted Calming Plush Teddy Bear (1.5kg)',
    category: 'Plush & Sensory Toys',
    brand: 'Snug Cuddle',
    supplier: 'SoftTouch Textiles',
    warehouse: 'Main Hub - Karachi',
    quantity: 0,
    minStock: 12,
    maxStock: 70,
    status: 'out_of_stock',
    isActive: true,
    notes: 'High demand calming plush. Urgent stock needed.',
    updatedAt: '2026-09-26',
    shopifySynced: true,
    shopifyStock: 0,
  },
  {
    id: 'prod-106',
    sku: 'SNP-RD-006',
    name: 'Vintage Toddler Foot-to-Floor Metal Ride-On Roadster',
    category: 'Ride-On & Active Play',
    brand: 'Snug Speedster',
    supplier: 'Alpha Wheels Ltd',
    warehouse: 'Main Hub - Karachi',
    quantity: 14,
    minStock: 5,
    maxStock: 30,
    status: 'in_stock',
    isActive: true,
    notes: 'Silent rubber tyres for indoor driving.',
    updatedAt: '2026-09-20',
    shopifySynced: true,
    shopifyStock: 14,
  },
]

export const INITIAL_SHOPIFY_ALERTS: ShopifySyncAlert[] = [
  {
    id: 'shp-alert-1',
    sku: 'SNP-GLIDER-99',
    title: 'Snug Wooden Indoor Toddler Slide & Glider',
    shopifyQuantity: 15,
    reason: 'missing_in_local',
    detectedAt: '2026-09-26 10:30 AM',
  },
]

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-901',
    productId: 'prod-101',
    productName: 'Pastel Modular Soft Play Climb & Crawl Set (5-Piece)',
    sku: 'SNP-SP-001',
    type: 'stock_in',
    quantity: 20,
    previousQuantity: 22,
    newQuantity: 42,
    reason: 'Received supplier shipment PO#4401',
    reference: 'PO-4401',
    date: '2026-09-25 02:30 PM',
    userName: 'Inventory Editor',
  },
  {
    id: 'tx-902',
    productId: 'prod-105',
    productName: 'Sensory Weighted Calming Plush Teddy Bear (1.5kg)',
    sku: 'SNP-PL-005',
    type: 'stock_out',
    quantity: 12,
    previousQuantity: 12,
    newQuantity: 0,
    reason: 'Dispatched preschool bulk order',
    reference: 'ORD-8821',
    date: '2026-09-26 09:10 AM',
    userName: 'Inventory Editor',
  },
]

export const INITIAL_BACKUPS: BackupItem[] = [
  {
    id: 'bcp-auto-20260901',
    name: 'Auto_Backup_Monthly_Sep2026.json',
    type: 'automated',
    status: 'completed',
    sizeKb: 88.4,
    recordsCount: 140,
    createdBy: 'System Automated Cron (30-Day)',
    createdAt: '2026-09-01 00:00:00',
    checksum: 'sha256-a9f82d8c3b77e',
  },
]

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-26 09:30:15',
    action: 'USER_LOGIN',
    module: 'Auth',
    description: 'System Admin signed in',
    userName: 'System Admin',
    userEmail: 'amankamran2004@outlook.com',
    role: 'system_admin',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-26 09:15:00',
    action: 'STOCK_SYNC',
    module: 'Shopify',
    description: 'Shopify live inventory synchronized (6 SKUs matched)',
    userName: 'System Admin',
    userEmail: 'amankamran2004@outlook.com',
    role: 'system_admin',
  },
]

export const INITIAL_SETTINGS: SystemSettings = {
  companyName: 'Snug N Play Toys & Play Gear',
  adminEmail: 'amankamran2004@outlook.com',
  autoBackupEnabled: true,
  backupFrequencyDays: 30,
  lastBackupDate: '2026-09-01',
  nextBackupDate: '2026-10-01',
  lowStockThresholdDefault: 10,
  shopifyConnected: true,
  shopifyStoreUrl: 'snugnplay.myshopify.com',
  theme: 'system',
}
