import { Product, User, Transaction, BackupItem, PasswordResetRequest, AuditLogItem, SystemSettings } from './types'

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'System Admin',
    email: 'amankamran2004@outlook.com',
    role: 'system_admin',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-26 09:30 AM',
    createdAt: '2026-01-01',
  },
  {
    id: 'usr-mgr-2',
    name: 'Sarah Khan (Manager)',
    email: 'manager@snugnplay.com',
    role: 'manager',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-25 04:15 PM',
    createdAt: '2026-01-10',
  },
  {
    id: 'usr-ops-3',
    name: 'Bilal Ahmed (Operations)',
    email: 'operations@snugnplay.com',
    role: 'operations',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-26 08:45 AM',
    createdAt: '2026-02-01',
  },
  {
    id: 'usr-acc-4',
    name: 'Zainab Tariq (Accounts)',
    email: 'accounts@snugnplay.com',
    role: 'accounts',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-24 11:20 AM',
    createdAt: '2026-02-15',
  },
]

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    sku: 'SNP-SP-001',
    name: 'Pastel Modular Soft Play Climb & Crawl Set (5-Piece)',
    category: 'Soft Play Equipment',
    brand: 'Snug N Play Original',
    supplier: 'PlaySafe Foam Ltd',
    warehouse: 'Main Hub - Karachi',
    quantity: 42,
    minStock: 10,
    maxStock: 100,
    unitCost: 14500,
    sellingPrice: 22999,
    status: 'in_stock',
    isActive: true,
    notes: 'Bestseller foam shapes with wipe-clean vegan leather cover.',
    updatedAt: '2026-09-25',
  },
  {
    id: 'prod-102',
    sku: 'SNP-BP-002',
    name: 'Luxury Velvet Ball Pit with 200 Non-Toxic Pearl Balls',
    category: 'Ball Pits & Playsets',
    brand: 'Snug N Play Luxury',
    supplier: 'SafePlast Toys',
    warehouse: 'Main Hub - Karachi',
    quantity: 18,
    minStock: 10,
    maxStock: 60,
    unitCost: 8200,
    sellingPrice: 13499,
    status: 'in_stock',
    isActive: true,
    notes: 'Memory foam base with washable OEKO-TEX velvet cover.',
    updatedAt: '2026-09-24',
  },
  {
    id: 'prod-103',
    sku: 'SNP-MAT-003',
    name: 'Double-Sided Foldable Waterproof Baby Play Mat (200x180cm)',
    category: 'Play Mats & Rugs',
    brand: 'Snug N Play Care',
    supplier: 'EcoFoam Industries',
    warehouse: 'Lahore Depot',
    quantity: 8,
    minStock: 15,
    maxStock: 80,
    unitCost: 4100,
    sellingPrice: 6999,
    status: 'low_stock',
    isActive: true,
    notes: 'XPE High-density foam, non-slip reversible cartoon & geometric design.',
    updatedAt: '2026-09-26',
  },
  {
    id: 'prod-104',
    sku: 'SNP-WD-004',
    name: 'Montessori Wooden Balance Board & Rocker (Natural Beechwood)',
    category: 'Wooden & Montessori Toys',
    brand: 'Snug Woodcraft',
    supplier: 'CraftWood Artisans',
    warehouse: 'Islamabad Center',
    quantity: 25,
    minStock: 8,
    maxStock: 50,
    unitCost: 5600,
    sellingPrice: 9499,
    status: 'in_stock',
    isActive: true,
    notes: 'Holds up to 100kg weight capacity with felt bottom layer.',
    updatedAt: '2026-09-22',
  },
  {
    id: 'prod-105',
    sku: 'SNP-PL-005',
    name: 'Sensory Weighted Calming Plush Teddy Bear (1.5kg)',
    category: 'Plush & Sensory Toys',
    brand: 'Snug Cuddle',
    supplier: 'SoftTouch Textiles',
    warehouse: 'Main Hub - Karachi',
    quantity: 0,
    minStock: 12,
    maxStock: 70,
    unitCost: 2800,
    sellingPrice: 4899,
    status: 'out_of_stock',
    isActive: true,
    notes: 'High demand for autism calming sensory therapy. Urgent PO required.',
    updatedAt: '2026-09-26',
  },
  {
    id: 'prod-106',
    sku: 'SNP-RD-006',
    name: 'Vintage Toddler Foot-to-Floor Metal Ride-On Roadster',
    category: 'Ride-On & Active Play',
    brand: 'Snug Speedster',
    supplier: 'Alpha Wheels Ltd',
    warehouse: 'Main Hub - Karachi',
    quantity: 14,
    minStock: 5,
    maxStock: 30,
    unitCost: 11200,
    sellingPrice: 17999,
    status: 'in_stock',
    isActive: true,
    notes: 'Chrome grille and rubber tyres for silent indoor driving.',
    updatedAt: '2026-09-20',
  },
  {
    id: 'prod-107',
    sku: 'SNP-ST-007',
    name: 'Anti-Slip Toddler Steps & Slide Soft Play Combo',
    category: 'Soft Play Equipment',
    brand: 'Snug N Play Original',
    supplier: 'PlaySafe Foam Ltd',
    warehouse: 'Lahore Depot',
    quantity: 6,
    minStock: 10,
    maxStock: 40,
    unitCost: 9800,
    sellingPrice: 15499,
    status: 'low_stock',
    isActive: true,
    notes: 'Perfect for nursery play corners and 1-3 age group.',
    updatedAt: '2026-09-26',
  },
  {
    id: 'prod-108',
    sku: 'SNP-PZ-008',
    name: 'Magnetic Wooden Alphabet & Number Activity Maze Board',
    category: 'Educational & Puzzles',
    brand: 'Snug Learn',
    supplier: 'BrightMinds Edu',
    warehouse: 'Islamabad Center',
    quantity: 65,
    minStock: 15,
    maxStock: 100,
    unitCost: 1650,
    sellingPrice: 2999,
    status: 'in_stock',
    isActive: true,
    notes: 'Fine motor development with magnetic stylus and enclosed acrylic top.',
    updatedAt: '2026-09-18',
  },
]

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-901',
    productId: 'prod-101',
    productName: 'Pastel Modular Soft Play Climb & Crawl Set (5-Piece)',
    sku: 'SNP-SP-001',
    type: 'stock_in',
    quantity: 20,
    previousQuantity: 22,
    newQuantity: 42,
    reason: 'Received supplier shipment PO#4401',
    reference: 'PO-4401',
    date: '2026-09-25 02:30 PM',
    userName: 'Bilal Ahmed (Operations)',
  },
  {
    id: 'tx-902',
    productId: 'prod-105',
    productName: 'Sensory Weighted Calming Plush Teddy Bear (1.5kg)',
    sku: 'SNP-PL-005',
    type: 'stock_out',
    quantity: 12,
    previousQuantity: 12,
    newQuantity: 0,
    reason: 'Dispatched bulk nursery preschool order',
    reference: 'ORD-8821',
    date: '2026-09-26 09:10 AM',
    userName: 'Bilal Ahmed (Operations)',
  },
  {
    id: 'tx-903',
    productId: 'prod-103',
    productName: 'Double-Sided Foldable Waterproof Baby Play Mat (200x180cm)',
    sku: 'SNP-MAT-003',
    type: 'damage',
    quantity: 2,
    previousQuantity: 10,
    newQuantity: 8,
    reason: 'Water leakage in warehouse section B',
    reference: 'DMG-109',
    date: '2026-09-26 08:00 AM',
    userName: 'Bilal Ahmed (Operations)',
  },
  {
    id: 'tx-904',
    productId: 'prod-102',
    productName: 'Luxury Velvet Ball Pit with 200 Non-Toxic Pearl Balls',
    sku: 'SNP-BP-002',
    type: 'stock_out',
    quantity: 5,
    previousQuantity: 23,
    newQuantity: 18,
    reason: 'Website customer dispatches',
    reference: 'DISP-773',
    date: '2026-09-24 04:45 PM',
    userName: 'Sarah Khan (Manager)',
  },
]

export const INITIAL_BACKUPS: BackupItem[] = [
  {
    id: 'bcp-auto-20260901',
    name: 'Auto_Backup_Monthly_Sep2026.json',
    type: 'automated',
    status: 'completed',
    sizeKb: 142.8,
    recordsCount: 184,
    createdBy: 'System Automated Cron (30-Day)',
    createdAt: '2026-09-01 00:00:00',
    checksum: 'sha256-a9f82d8c3b77e',
  },
  {
    id: 'bcp-auto-20260801',
    name: 'Auto_Backup_Monthly_Aug2026.json',
    type: 'automated',
    status: 'completed',
    sizeKb: 138.4,
    recordsCount: 176,
    createdBy: 'System Automated Cron (30-Day)',
    createdAt: '2026-08-01 00:00:00',
    checksum: 'sha256-88d01ef45bc21',
  },
  {
    id: 'bcp-man-20260920',
    name: 'Pre_StockAudit_Manual_Snapshot.json',
    type: 'manual',
    status: 'completed',
    sizeKb: 145.2,
    recordsCount: 189,
    createdBy: 'System Admin (amankamran2004@outlook.com)',
    createdAt: '2026-09-20 03:15 PM',
    checksum: 'sha256-f44299bcae129',
  },
]

export const INITIAL_RESET_REQUESTS: PasswordResetRequest[] = [
  {
    id: 'rst-101',
    referenceCode: 'RST-99420',
    userId: 'usr-ops-3',
    userEmail: 'operations@snugnplay.com',
    userName: 'Bilal Ahmed (Operations)',
    status: 'pending',
    requestedAt: '2026-09-26 07:45 AM',
    notes: 'Forgot password after device reset. Please send new temporary password.',
  },
]

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-26 09:30:15',
    action: 'USER_LOGIN',
    module: 'Auth',
    description: 'System Admin signed in successfully',
    userName: 'System Admin',
    userEmail: 'amankamran2004@outlook.com',
    role: 'system_admin',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-26 09:10:44',
    action: 'STOCK_OUT',
    module: 'Stock',
    description: 'Dispatched 12 units of SKU SNP-PL-005 (Preschool Order)',
    userName: 'Bilal Ahmed',
    userEmail: 'operations@snugnplay.com',
    role: 'operations',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-25 02:30:11',
    action: 'STOCK_IN',
    module: 'Stock',
    description: 'Added 20 units of SKU SNP-SP-001 (PO-4401)',
    userName: 'Bilal Ahmed',
    userEmail: 'operations@snugnplay.com',
    role: 'operations',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-20 03:15:00',
    action: 'BACKUP_CREATED',
    module: 'Backup',
    description: 'Manual snapshot generated and exported (145.2 KB)',
    userName: 'System Admin',
    userEmail: 'amankamran2004@outlook.com',
    role: 'system_admin',
  },
]

export const INITIAL_SETTINGS: SystemSettings = {
  companyName: 'Snug N Play Toys & Play Gear',
  adminEmail: 'amankamran2004@outlook.com',
  currency: 'PKR',
  currencySymbol: 'Rs.',
  autoBackupEnabled: true,
  backupFrequencyDays: 30,
  lastBackupDate: '2026-09-01',
  nextBackupDate: '2026-10-01',
  lowStockThresholdDefault: 10,
  theme: 'system',
}
